spring.application.name=alumni-hub

# Database Configuration (Resolves variables parsed from DATABASE_URL at runtime)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Firebase Configuration
firebase.project-id=${FIREBASE_PROJECT_ID}
firebase.client-email=${FIREBASE_CLIENT_EMAIL}
firebase.private-key=${FIREBASE_PRIVATE_KEY}
